version: '2.2'
services:

  nodered:
    container_name: nodered
    restart: always
    image: "dpflores/nodered_acme:base"
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    networks:
      - web_network
      
  nginx:
    container_name: nginx1
    restart: always
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - nodered
  
 
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
volumes:
  node-red-data: